// automatically generated by build_post_index.js
export default [
  {
    filePath: 'pages/blog/first.mdx',
    urlPath: '/blog/first',
    title: 'First Post',
    publishDate: '2018-05-10T12:00:00.000Z'
  },
  {
    filePath: 'pages/blog/second.mdx',
    urlPath: '/blog/second',
    title: '2 Post',
    publishDate: '2018-05-10T12:00:00.000Z'
  },
  {
    filePath: 'pages/blog/third.mdx',
    urlPath: '/blog/third',
    title: '3 Post',
    publishDate: '2018-05-10T12:00:00.000Z'
  }
];
